
@baseUrl = http://localhost:3000
#@authToken = {{SESSION.response.body.$.token}}
@id = fe0c9f0a-8cd2-4551-9966-cbd4f4983a55

#PRODUCT

# @name CREATE
POST {{baseUrl}}/product 
Content-Type: application/json

{
    "name": "Product 3",
    "price": 100,
    "quantity": 10
}
###
# @name LIST
GET {{baseUrl}}/product
###
# @name GET
GET {{baseUrl}}/product/{{id}}
###
# @name UPDATE
PATCH  {{baseUrl}}/product/{{id}}
Content-Type: application/json

{
    "quantity": 11
}