
@baseUrl = http://localhost:3000
@authToken = {{SESSION.response.body.$.token}}
@id = 59714a34-29ff-4e83-8455-998404f63b4f

# @name SESSION
POST {{baseUrl}}/user/login
Content-Type: application/json

{
    "email": "user2@mail.com",
    "password": "12345"
}
###

# USER
# @name CREATE
POST {{baseUrl}}/user
Content-Type: application/json

{
    "name": "User 2",
    "email": "user2@mail.com",
    "age": 20,
    "cpf": "12345678902",
    "password": "12345"
} 
###
# @name LIST
GET {{baseUrl}}/user
###
# @name GET
GET {{baseUrl}}/user/{{id}}
###
# @name UPDATE
PATCH {{baseUrl}}/user/{{id}}
Content-Type: application/json

{
    "name": "User 2",
    "email": "user2@mail.com",
    "password": "12345",
    "old_password": "12345"
}
###
# @name DELETE
DELETE {{baseUrl}}/user/{{id}}
###
# @name PROFILE
GET {{baseUrl}}/user/profile
Authorization: Bearer {{authToken}}