
@baseUrl = http://localhost:3000
@authToken = {{SESSION.response.body.$.token}}
@id = 46b2bb60-a247-474d-bc31-0bfe8ba94808

#PRODUCT

# @name CREATE
POST {{baseUrl}}/product 
Content-Type: application/json

{
    "name": "Product 3",
    "price": 100,
    "quantity": 10
}
###
# @name LIST
GET {{baseUrl}}/product
###
# @name GET
GET {{baseUrl}}/product/{{id}}
###
# @name UPDATE
PATCH  {{baseUrl}}/product/{{id}}
Content-Type: application/json

{
    "quantity": 11
}

###
# USER
# @name CREATE
POST {{baseUrl}}/user
Content-Type: application/json

{
    "name": "User 2",
    "email": "user2@mail.com",
    "age": 20,
    "cpf": "12345678902",
    "password": "12345"
} 
###
# @name LIST
GET {{baseUrl}}/user
###
# @name GET
GET {{baseUrl}}/user/{{id}}
###
# @name UPDATE
PATCH {{baseUrl}}/user/{{id}}
Content-Type: application/json

{
    "name": "User 2",
    "email": "user2@mail.com",
    "password": "12345",
    "old_password": "12345"
}
###
# @name DELETE
DELETE {{baseUrl}}/user/{{id}}
###
# @name SESSION
POST {{baseUrl}}/user/login
Content-Type: application/json

{
    "email": "user2@mail.com",
    "password": "12345"
}
###
# @name PROFILE
GET {{baseUrl}}/user/profile
Authorization: Bearer {{authToken}}